"""
Generate nutrition labels (stunting, underweight, wasting) from PDF-derived lookup tables.

Uses: data/processed/stunting_lookup.csv, underweight_lookup.csv, wasting_lookup.csv
(Generated by scripts/parse_assessment_pdfs.py)

Definitions:
- Stunting (underheight): height-for-age; compare child's height to threshold for (sex, age_days).
- Underweight: weight-for-age; compare child's weight to threshold for (sex, age_days).
- Wasting / SAM / MAM: weight-for-height; compare child's weight to thresholds for (sex, age_band, height_cm).
"""

from __future__ import annotations

import csv
from pathlib import Path

# Default paths relative to project root (this file: src/utils/nutrition_labels.py)
PROJECT_ROOT = Path(__file__).resolve().parents[2]
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"


def _load_stunting_lookup(path: Path | None = None) -> dict[tuple[str, int], tuple[float, float]]:
    """(sex, day) -> (h_severe_max, h_normal_min)."""
    path = path or PROCESSED_DIR / "stunting_lookup.csv"
    out = {}
    with open(path) as f:
        r = csv.DictReader(f)
        for row in r:
            key = (row["sex"].strip().upper() or "M", int(row["day"]))
            out[key] = (float(row["h_severe_max"]), float(row["h_normal_min"]))
    return out


def _load_underweight_lookup(path: Path | None = None) -> dict[tuple[str, int], tuple[float, float]]:
    """(sex, day) -> (w_severe_max, w_normal_min)."""
    path = path or PROCESSED_DIR / "underweight_lookup.csv"
    out = {}
    with open(path) as f:
        r = csv.DictReader(f)
        for row in r:
            key = (row["sex"].strip().upper() or "M", int(row["day"]))
            out[key] = (float(row["w_severe_max"]), float(row["w_normal_min"]))
    return out


def _load_wasting_lookup(path: Path | None = None) -> dict[tuple[str, str, float], tuple[float, float, float, float]]:
    """(sex, age_band, height_cm) -> (sam_upper, mam_upper, normal_upper, overweight_upper)."""
    path = path or PROCESSED_DIR / "wasting_lookup.csv"
    out = {}
    with open(path) as f:
        r = csv.DictReader(f)
        for row in r:
            sex = (row["sex"].strip().upper() or "M")
            age_band = row["age_band"].strip()
            height_cm = round(float(row["height_cm"]), 1)
            key = (sex, age_band, height_cm)
            out[key] = (
                float(row["sam_upper"]),
                float(row["mam_upper"]),
                float(row["normal_upper"]),
                float(row["overweight_upper"]),
            )
    return out


# Module-level caches (lazy load)
_stunting: dict | None = None
_underweight: dict | None = None
_wasting: dict | None = None


def _get_stunting_table():
    global _stunting
    if _stunting is None:
        _stunting = _load_stunting_lookup()
    return _stunting


def _get_underweight_table():
    global _underweight
    if _underweight is None:
        _underweight = _load_underweight_lookup()
    return _underweight


def _get_wasting_table():
    global _wasting
    if _wasting is None:
        _wasting = _load_wasting_lookup()
    return _wasting


def _nearest_day(sex: str, day: int, table: dict) -> tuple[float, float] | None:
    """Return (threshold1, threshold2) for nearest day in table, or None."""
    key_exact = (sex, day)
    if key_exact in table:
        return table[key_exact]
    days_for_sex = sorted(d for (s, d) in table if s == sex)
    if not days_for_sex:
        return None
    if day <= days_for_sex[0]:
        return table[(sex, days_for_sex[0])]
    if day >= days_for_sex[-1]:
        return table[(sex, days_for_sex[-1])]
    # binary search for nearest
    lo, hi = 0, len(days_for_sex) - 1
    while hi - lo > 1:
        mid = (lo + hi) // 2
        if days_for_sex[mid] <= day:
            lo = mid
        else:
            hi = mid
    d_lo, d_hi = days_for_sex[lo], days_for_sex[hi]
    return table[(sex, d_hi)] if (day - d_lo) > (d_hi - day) else table[(sex, d_lo)]


def _nearest_height(sex: str, age_band: str, height_cm: float, table: dict) -> tuple[float, float, float, float] | None:
    """Return (sam_upper, mam_upper, normal_upper, overweight_upper) for nearest height, or None."""
    height_round = round(height_cm, 1)
    key = (sex, age_band, height_round)
    if key in table:
        return table[key]
    keys_same_sex_band = [(s, ab, h) for (s, ab, h) in table if s == sex and ab == age_band]
    if not keys_same_sex_band:
        return None
    heights = sorted(h for (_, _, h) in keys_same_sex_band)
    if height_cm <= heights[0]:
        return table[(sex, age_band, heights[0])]
    if height_cm >= heights[-1]:
        return table[(sex, age_band, heights[-1])]
    # nearest
    best = min(heights, key=lambda h: abs(h - height_cm))
    return table[(sex, age_band, best)]


def age_days_to_wasting_band(age_days: int) -> str:
    """Map age in days to wasting lookup band: 0-2 yrs or 2-5 yrs."""
    if age_days <= 730:
        return "0-2"
    return "2-5"


def classify_stunting(sex: str, age_days: int, height_cm: float | None) -> tuple[str | None, bool | None]:
    """
    Returns (stunting_status, is_stunted).
    status: 'normal' | 'moderately_stunted' | 'severely_stunted'
    is_stunted is None when classification inputs are missing/invalid.
    """
    if height_cm is None or height_cm <= 0:
        return None, None
    sex = "M" if sex not in ("M", "F") else sex
    table = _get_stunting_table()
    row = _nearest_day(sex, age_days, table)
    if row is None:
        return None, None
    h_severe_max, h_normal_min = row
    if height_cm <= h_severe_max:
        return "severely_stunted", True
    if height_cm <= h_normal_min:
        return "moderately_stunted", True
    return "normal", False


def classify_underweight(sex: str, age_days: int, weight_kg: float | None) -> tuple[str | None, bool | None]:
    """
    Returns (underweight_status, is_underweight).
    status: 'normal' | 'moderately_underweight' | 'severely_underweight'
    is_underweight is None when classification inputs are missing/invalid.
    """
    if weight_kg is None or weight_kg <= 0:
        return None, None
    sex = "M" if sex not in ("M", "F") else sex
    table = _get_underweight_table()
    row = _nearest_day(sex, age_days, table)
    if row is None:
        return None, None
    w_severe_max, w_normal_min = row
    if weight_kg <= w_severe_max:
        return "severely_underweight", True
    if weight_kg <= w_normal_min:
        return "moderately_underweight", True
    return "normal", False


def classify_wasting(
    sex: str,
    age_days: int,
    height_cm: float | None,
    weight_kg: float | None,
) -> tuple[str | None, bool | None, bool | None]:
    """
    Returns (wasting_status, is_wasted, is_sam).
    status: 'SAM' | 'MAM' | 'normal' | 'overweight' | 'obese'
    is_wasted/is_sam are None when classification inputs are missing/invalid.
    """
    if height_cm is None or height_cm <= 0 or weight_kg is None or weight_kg <= 0:
        return None, None, None
    sex = "M" if sex not in ("M", "F") else sex
    age_band = age_days_to_wasting_band(age_days)
    table = _get_wasting_table()
    row = _nearest_height(sex, age_band, height_cm, table)
    if row is None:
        return None, None, None
    sam_upper, mam_upper, normal_upper, overweight_upper = row
    if weight_kg <= sam_upper:
        return "SAM", True, True
    if weight_kg <= mam_upper:
        return "MAM", True, False
    if weight_kg <= normal_upper:
        return "normal", False, False
    if weight_kg <= overweight_upper:
        return "overweight", False, False
    return "obese", False, False


def classify_all(
    sex: str,
    age_days: int,
    height_cm: float | None,
    weight_kg: float | None,
) -> dict:
    """
    One-shot classification for a single measurement.
    Returns dict with keys: stunting_status, is_stunted, underweight_status, is_underweight,
    wasting_status, is_wasted, is_sam.
    """
    st_status, is_st = classify_stunting(sex, age_days, height_cm)
    uw_status, is_uw = classify_underweight(sex, age_days, weight_kg)
    waste_status, is_wasted, is_sam = classify_wasting(sex, age_days, height_cm, weight_kg)
    return {
        "stunting_status": st_status,
        "is_stunted": is_st,
        "underweight_status": uw_status,
        "is_underweight": is_uw,
        "wasting_status": waste_status,
        "is_wasted": is_wasted,
        "is_sam": is_sam,
    }
